version: "3"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      APP_NAME: ${APP_NAME}
      PORT: ${PORT}
      DB_URI: ${DB_URI}
    depends_on:
      - mongo_db
